[theme]
base="light"                # or "dark"
primaryColor="#1E90FF"      # Main accent color
backgroundColor="#FFFFFF"  # App background
secondaryBackgroundColor="#F0F2F6"  # Sidebar or other secondary sections
textColor="#262730"        # Main text
font="sans serif"          # Options: "sans serif", "serif", "monospace"